import { fetchPage } from "./http.js";

export type LivenessState =
  | "live"
  /** A server answered but refused an automated client — the site is real. */
  | "protected"
  | "parked"
  | "placeholder"
  | "http_error"
  | "unreachable";

export interface LivenessResult {
  state: LivenessState;
  /** HTTP status of the final response, when there was one. */
  status: number | null;
  /** URL after redirects, so an off-site parking redirect is visible. */
  finalUrl: string | null;
  /** Scheme that answered, when one did. */
  scheme: "https" | "http" | null;
}

/** Hosts that a for-sale or parked domain typically redirects to. */
const PARKING_HOSTS = [
  "sedoparking.com", "sedo.com", "afternic.com", "dan.com", "hugedomains.com",
  "undeveloped.com", "bodis.com", "parkingcrew.net", "above.com",
  "domainmarket.com", "buydomains.com", "namesilo.com/parked",
  "cashparking.com", "parked.com", "domainnameshop.com",
];

/** Phrases that only appear on a domain-for-sale or parking page. */
const PARKING_MARKERS = [
  "this domain is for sale", "this domain may be for sale", "buy this domain",
  "domain is for sale", "the domain name you are looking for is for sale",
  "domain for sale", "inquire about this domain", "make an offer on this domain",
  "parked free", "domain parking", "this webpage was generated by the domain owner",
  "courtesy of godaddy", "future home of something quite cool",
];

/** Phrases that mean a real site is planned but not yet there. */
const PLACEHOLDER_MARKERS = [
  "coming soon", "under construction", "site is being built",
  "website is under development", "launching soon", "be right back",
  "default web site page", "welcome to nginx", "apache2 ubuntu default page",
  "it works!", "index of /",
];

export interface LivenessOptions {
  timeoutMs: number;
}

export class LivenessChecker {
  constructor(private readonly options: LivenessOptions) {}

  /** Tries HTTPS first, then HTTP. A domain that answers on neither is dead. */
  async check(hostname: string): Promise<LivenessResult> {
    let lastState: LivenessResult | null = null;

    for (const scheme of ["https", "http"] as const) {
      try {
        const response = await fetchPage(`${scheme}://${hostname}/`, {
          timeoutMs: this.options.timeoutMs,
        });

        const state = classify(response.status, response.finalUrl, response.body);

        // An HTTPS error is worth a second opinion over HTTP before we judge;
        // anything conclusive we report straight away.
        if ((state === "http_error" || state === "protected") && scheme === "https") {
          lastState = { state, status: response.status, finalUrl: response.finalUrl, scheme };
          continue;
        }

        return {
          state,
          status: response.status,
          finalUrl: response.finalUrl,
          scheme,
        };
      } catch {
        continue;
      }
    }

    // Falling through means only inconclusive answers; report the best one we
    // saw rather than claiming the site is dead.
    return (
      lastState ?? { state: "unreachable", status: null, finalUrl: null, scheme: null }
    );
  }
}

/**
 * Bot protection (Cloudflare, Akamai, WAFs) routinely answers an unknown user
 * agent with these. They prove a server is there, so treating them as "dead"
 * would wrongly condemn plenty of real company websites.
 */
const PROTECTED_STATUSES = new Set([401, 403, 406, 429, 503]);

function classify(status: number, finalUrl: string, body: string): LivenessState {
  const haystack = body.toLowerCase();

  let finalHost = "";
  try {
    finalHost = new URL(finalUrl).hostname.toLowerCase();
  } catch {
    // Keep finalHost empty; the body markers still apply.
  }

  if (PARKING_HOSTS.some((host) => finalHost.endsWith(host) || finalUrl.includes(host))) {
    return "parked";
  }
  if (PARKING_MARKERS.some((marker) => haystack.includes(marker))) {
    return "parked";
  }

  if (PROTECTED_STATUSES.has(status)) return "protected";
  if (status >= 400) return "http_error";

  if (PLACEHOLDER_MARKERS.some((marker) => haystack.includes(marker))) {
    return "placeholder";
  }

  // A 200 with almost no markup is a stub, not a company website.
  if (haystack.trim().length < 200) return "placeholder";

  return "live";
}
